/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watermark-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Watermark Preview */
        post: operations["watermark_preview_api_v1_watermark_previews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watermarked-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Watermarked Image */
        post: operations["create_watermarked_image_api_v1_watermarked_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watermark-extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Watermark */
        post: operations["extract_watermark_api_v1_watermark_extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/legacy-watermark-extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Legacy Extract Watermark */
        post: operations["legacy_extract_watermark_api_v1_legacy_watermark_extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Login */
        post: operations["admin_login_api_v1_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Records */
        get: operations["admin_list_records_api_v1_admin_audit_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-records/{audit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Record */
        get: operations["admin_get_record_api_v1_admin_audit_records__audit_id__get"];
        put?: never;
        post?: never;
        /** Admin Delete Record */
        delete: operations["admin_delete_record_api_v1_admin_audit_records__audit_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-records/{audit_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Artifacts */
        get: operations["admin_list_artifacts_api_v1_admin_audit_records__audit_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Download Artifact */
        get: operations["admin_download_artifact_api_v1_admin_artifacts__artifact_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-records/{audit_id}/passphrase-reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Reveal Passphrase */
        post: operations["admin_reveal_passphrase_api_v1_admin_audit_records__audit_id__passphrase_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Original Name */
            original_name: string;
            /** Mime */
            mime: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
            /** Created At */
            created_at: string;
        };
        /** AuditRecordDetail */
        AuditRecordDetail: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string;
            /** Operation */
            operation: string;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Client Ip */
            client_ip: string;
            /** Direct Ip */
            direct_ip: string;
            /** Forwarded Chain */
            forwarded_chain: string[];
            /** User Agent */
            user_agent: string;
            /** Status */
            status: string;
            /** Http Status */
            http_status: number | null;
            /** Error Code */
            error_code: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Input Files */
            input_files: {
                [key: string]: unknown;
            }[];
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** AuditRecordList */
        AuditRecordList: {
            /** Items */
            items: components["schemas"]["AuditRecordSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** AuditRecordSummary */
        AuditRecordSummary: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string;
            /** Operation */
            operation: string;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Client Ip */
            client_ip: string;
            /** Status */
            status: string;
            /** Http Status */
            http_status: number | null;
            /** Error Code */
            error_code: string | null;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** Body_create_watermarked_image_api_v1_watermarked_images_post */
        Body_create_watermarked_image_api_v1_watermarked_images_post: {
            /**
             * Cover Image
             * Format: binary
             */
            cover_image: string;
            /**
             * Watermark Type
             * @enum {string}
             */
            watermark_type: "text" | "image";
            /**
             * Watermark Text
             * @default
             */
            watermark_text: string;
            /** Watermark Image */
            watermark_image?: string | null;
            /**
             * Passphrase
             * @default
             */
            passphrase: string;
        };
        /** Body_extract_watermark_api_v1_watermark_extractions_post */
        Body_extract_watermark_api_v1_watermark_extractions_post: {
            /**
             * Encoded Image
             * Format: binary
             */
            encoded_image: string;
            /**
             * Passphrase
             * @default
             */
            passphrase: string;
        };
        /** Body_legacy_extract_watermark_api_v1_legacy_watermark_extractions_post */
        Body_legacy_extract_watermark_api_v1_legacy_watermark_extractions_post: {
            /**
             * Encoded Image
             * Format: binary
             */
            encoded_image: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "text" | "image";
            /** Password Img */
            password_img: number;
            /** Password Wm */
            password_wm: number;
            /** Bit Length */
            bit_length?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
        };
        /** Body_watermark_preview_api_v1_watermark_previews_post */
        Body_watermark_preview_api_v1_watermark_previews_post: {
            /**
             * Cover Image
             * Format: binary
             */
            cover_image: string;
            /**
             * Watermark Image
             * Format: binary
             */
            watermark_image: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Api Version
             * @default v1
             */
            api_version: string;
            /** Formats */
            formats: string[];
            /** Output Format */
            output_format: string;
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Max Pixels */
            max_pixels: number;
            /** Watermark Types */
            watermark_types: string[];
            /** Legacy Decode */
            legacy_decode: boolean;
            /** Storage Mode */
            storage_mode: string;
        };
        /** DeleteAuditRequest */
        DeleteAuditRequest: {
            /** Reason */
            reason: string;
        };
        /** ExtractionResponse */
        ExtractionResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "image";
            /** Text */
            text?: string | null;
            /** Image Data Url */
            image_data_url?: string | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PassphraseRevealResponse */
        PassphraseRevealResponse: {
            /** Passphrase */
            passphrase: string;
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Image Data Url */
            image_data_url: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Resized */
            resized: boolean;
            /** Capacity Bits */
            capacity_bits: number;
            /** Used Bits */
            used_bits: number;
        };
        /** ProblemDetail */
        ProblemDetail: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Code */
            code: string;
            /** Request Id */
            request_id?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    watermark_preview_api_v1_watermark_previews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_watermark_preview_api_v1_watermark_previews_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_watermarked_image_api_v1_watermarked_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_watermarked_image_api_v1_watermarked_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_watermark_api_v1_watermark_extractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_watermark_api_v1_watermark_extractions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_extract_watermark_api_v1_legacy_watermark_extractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_legacy_extract_watermark_api_v1_legacy_watermark_extractions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_login_api_v1_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_records_api_v1_admin_audit_records_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                operation?: string | null;
                status?: string | null;
                query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecordList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_record_api_v1_admin_audit_records__audit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecordDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_record_api_v1_admin_audit_records__audit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_artifacts_api_v1_admin_audit_records__audit_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_download_artifact_api_v1_admin_artifacts__artifact_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_reveal_passphrase_api_v1_admin_audit_records__audit_id__passphrase_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassphraseRevealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
